services:

  web:
    build: .
    pull_policy: build
    restart: always
    command: gunicorn chudartz.wsgi:application --bind 0.0.0.0:8003
    env_file: stack.env

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8003:8003"
    working_dir: /app

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - nginx_volume:/etc/nginx
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "81:81"

volumes:
  nginx_volume:
  media_volume:
  static_volume: