"""
Django settings for chudartz project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", False)

ALLOWED_HOSTS = ['192.168.86.200', '0.0.0.0', 'localhost', '127.0.0.1', 'chudartz.com', 'chudartz-collectibles.com']
CSRF_TRUSTED_ORIGINS = ['https://chudartz.com', 'https://chudartz-collectibles.com', 'http://localhost:81']

DBBACKUP_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DBBACKUP_STORAGE_OPTIONS = {
    'access_key': os.environ.get('AWS_ACCESS_KEY'), 
    'secret_key': os.environ.get('AWS_SECRET_KEY'),
    'bucket_name': os.environ.get('AWS_STORAGE_BUCKET_NAME'),
    'default_acl': 'private',
    'location': 'backups',
    'region_name': os.environ.get('AWS_S3_REGION_NAME', default='us-east-1'),
}

# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.inlines",  
    "unfold.contrib.simple_history",
    "unfold.contrib.import_export",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'darts',
    'pokemon',

    'simple_history',
    'dbbackup',
    'storages',
    'djmoney',
    'ckeditor',
    'lockdown',
    'phonenumber_field',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'darts.middleware.DomainMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'lockdown.middleware.LockdownMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chudartz.wsgi.application'

ROOT_URLCONF='chudartz.urls'

# Lockdown
LOCKDOWN_ENABLED = os.environ.get("LOCKDOWN_ENABLED", False)
LOCKDOWN_PASSWORDS = (os.environ.get("LOCKDOWN_PASS"),)

LOCKDOWN_URL_EXCEPTIONS = (
    r'^/static/',
    r'cal-webhook/',
    r'mollie-webhook/'
)

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': 'db',
        'PORT': 5432,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

USE_TZ = True
TIME_ZONE = 'Europe/Brussels'

USE_I18N = True
LANGUAGE_CODE = 'nl'

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

LANGUAGES = [
    ('nl', 'Nederlands'),
    ('en', 'English'),
    ('fr', 'Français')
]

# Emailing

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
PHONENUMBER_DEFAULT_REGION = 'BE'

# Unfold

UNFOLD = {
    "SITE_TITLE": "Chudartz Admin",
    "SITE_HEADER": "Chudartz Admin",
    "SITE_URL": "/",

    "SITE_LOGO": lambda request: static("img/logo-black.png"),

    "SITE_SYMBOL": "target",
    "SHOW_HISTORY": True, 
    "SHOW_VIEW_ON_SITE": True,

    "COLORS": {
        "primary": {
            "50": "255 237 237",
            "100": "255 204 204",
            "200": "255 170 170",
            "300": "255 136 136",
            "400": "255 102 102",
            "500": "195 17 26",
            "600": "174 15 23",
            "700": "154 13 21",
            "800": "134 11 19",
            "900": "115 9 17",
            "950": "96 7 15",
        },
    },
    
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": True,
        "navigation": [

            {
                "items": [
                    {
                        "title": _("Financiën"),
                        "icon": "payments",
                        "link": "https://my.mollie.com/dashboard/org_19161509/home",
                    },
                    {
                        "title": _("Analyse"),
                        "icon": "query_stats",
                        "link": "https://analytics.google.com/",
                    },
                ]
            },
            
            {
                "title": "Darts",
                "separator": True,
                "items": [
                    {
                        "title": _("Toernooien"),
                        "icon": "trophy",
                        "link": "/admin/darts/toernooi/",
                    },

                    {
                        "title": _("Deelnemers"),
                        "icon": "group",
                        "link": "/admin/darts/participant/",
                    },

                    {
                        "title": _("Scanner"),
                        "icon": "qr_code_scanner",
                        "link": "https://chudartz.com/darts/scanner/",
                    },
                ],
            },

            {
                "separator": True,
                "items": [
                    {
                        "title": _("Dartschool"),
                        "icon": "school",
                        "link": "https://app.cal.com/bookings/upcoming",
                    },

                    {
                        "title": _("Leerlingen"),
                        "icon": "patient_list",
                        "link": "/admin/darts/leerling/",
                    },

                    {
                        "title": _("Trainers"),
                        "icon": "sports",
                        "link": "/admin/darts/trainer/",
                    },

                    {
                        "title": _("Beurtkaarten"),
                        "icon": "confirmation_number",
                        "link": "/admin/darts/beurtkaart/",
                    },
                ]
            },

            {
                "separator": True,
                "items": [
                    {
                        "title": _("Sponsors"),
                        "icon": "checkbook",
                        "link": "/admin/darts/sponsor/",
                    },
                    {
                        "title": _("Nieuws"),
                        "icon": "article",
                        "link": "/admin/darts/nieuws/"
                    },
                    {
                        "title": _("Navigatiebalk"),
                        "icon": "dropdown",
                        "link": "/admin/darts/toernooiheadergroep/",
                    },

                ]
            },

            {
                "title": "Collectibles",
                "separator": True,
                "items": [
                    {
                        "title": _("Evenementen"),
                        "icon": "festival",
                        "link": "/admin/pokemon/evenement",
                    },
                    {
                        "title": _("Deelnemers"),
                        "icon": "group",
                        "link": "/admin/pokemon/participant",
                    },
                    {
                        "title": _("Partners"),
                        "icon": "partner_exchange",
                        "link": "/admin/pokemon/partner",
                    },
                    {
                        "title": _("Scanner"),
                        "icon": "qr_code_scanner",
                        "link": "https://chudartz-collectibles.com/pokemon/scanner/",
                    },
                ]
            },

        ],
    },
}