# Generated by Django 5.0.6 on 2024-08-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='vereisten',
            field=models.TextField(default='', verbose_name='Vereisten (Elk op een nieuwe lijn)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='vereisten',
            field=models.TextField(default='', verbose_name='Vereisten (Elk op een nieuwe lijn)'),
            preserve_default=False,
        ),
    ]
