# Generated by Django 5.0.6 on 2024-08-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0002_evenement_vereisten_historicalevenement_vereisten'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='afbeeldingen_download_url',
            field=models.URLField(blank=True, null=True, verbose_name='Download afbeeldingen URL'),
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='afbeeldingen_download_url',
            field=models.URLField(blank=True, null=True, verbose_name='Download afbeeldingen URL'),
        ),
    ]
