# Generated by Django 5.0.6 on 2024-08-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0003_evenement_afbeeldingen_download_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipant',
            name='nummer',
            field=models.CharField(default='5', max_length=6, verbose_name='Nummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalparticipant',
            name='stad',
            field=models.CharField(default='5', max_length=40, verbose_name='Stad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalparticipant',
            name='straatnaam',
            field=models.CharField(default='', max_length=100, verbose_name='Straatnaam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='nummer',
            field=models.CharField(default='', max_length=6, verbose_name='Nummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='stad',
            field=models.CharField(default='', max_length=40, verbose_name='Stad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='straatnaam',
            field=models.CharField(default='', max_length=100, verbose_name='Straatnaam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evenement',
            name='locatie_lang',
            field=models.TextField(verbose_name='Locatie (lang)'),
        ),
        migrations.AlterField(
            model_name='historicalevenement',
            name='locatie_lang',
            field=models.TextField(verbose_name='Locatie (lang)'),
        ),
        migrations.AlterField(
            model_name='historicalparticipant',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Attended'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Attended'),
        ),
    ]
