# Generated by Django 5.0.6 on 2024-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0005_rename_last_name_historicalparticipant_achternaam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='vereist_voogd_toestemming',
            field=models.BooleanField(default=False, verbose_name='Toestemming van voogd verist'),
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='vereist_voogd_toestemming',
            field=models.BooleanField(default=False, verbose_name='Toestemming van voogd verist'),
        ),
    ]
