# Generated by Django 5.0.6 on 2024-08-25 18:59

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0007_sponsor_historicalsponsor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leerling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=50, verbose_name='Voornaam')),
                ('achternaam', models.CharField(max_length=50, verbose_name='Achternaam')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('extra_info', ckeditor.fields.RichTextField(verbose_name='Extra Info')),
                ('resterende_beurten', models.PositiveSmallIntegerField(default=5, verbose_name='Resterende Beuren')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Code')),
            ],
        ),
        migrations.AlterModelOptions(
            name='evenement',
            options={'get_latest_by': 'start_datum', 'ordering': ['-start_datum']},
        ),
        migrations.CreateModel(
            name='HistoricalLeerling',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=50, verbose_name='Voornaam')),
                ('achternaam', models.CharField(max_length=50, verbose_name='Achternaam')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('extra_info', ckeditor.fields.RichTextField(verbose_name='Extra Info')),
                ('resterende_beurten', models.PositiveSmallIntegerField(default=5, verbose_name='Resterende Beuren')),
                ('code', models.CharField(db_index=True, max_length=6, verbose_name='Code')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'historical leerlings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
