# Generated by Django 5.0.6 on 2024-08-25 19:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0008_leerling_alter_evenement_options_historicalleerling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleerling',
            name='extra_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Extra Info'),
        ),
        migrations.AlterField(
            model_name='leerling',
            name='extra_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Extra Info'),
        ),
    ]
