# Generated by Django 5.0.6 on 2024-08-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0011_rename_historicalevenement_historicaltornooi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschrijving'),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschrijving'),
        ),
    ]
