# Generated by Django 5.0.6 on 2024-08-30 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0012_darts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeurtkaartBetaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betaling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darts.payment', verbose_name='Betaling')),
                ('beurtkaart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darts.beurtkaart', verbose_name='Beurtkaart')),
                ('leerling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darts.leerling', verbose_name='Leerling')),
            ],
        ),
    ]
