# Generated by Django 5.0.6 on 2024-08-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0013_beurtkaartbetaling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleerling',
            name='resterende_beurten',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Resterende Beurten'),
        ),
        migrations.AlterField(
            model_name='leerling',
            name='resterende_beurten',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Resterende Beurten'),
        ),
    ]
