# Generated by Django 5.0.6 on 2024-08-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0014_alter_historicalleerling_resterende_beurten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleerling',
            name='payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='darts.payment', verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='leerling',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='darts.payment', verbose_name='Payment'),
        ),
    ]
