# Generated by Django 5.0.6 on 2024-09-14 05:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0015_historicalleerling_payment_leerling_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalTornooi',
            new_name='HistoricalToernooi',
        ),
        migrations.RenameModel(
            old_name='Tornooi',
            new_name='Toernooi',
        ),
        migrations.AlterModelOptions(
            name='beurtkaart',
            options={'verbose_name': 'Beurtkaart', 'verbose_name_plural': 'Beurtkaarten'},
        ),
        migrations.AlterModelOptions(
            name='historicalbeurtkaart',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History', 'verbose_name_plural': 'historical Beurtkaarten'},
        ),
        migrations.AlterModelOptions(
            name='historicalleerling',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History', 'verbose_name_plural': 'historical Leerlingen'},
        ),
        migrations.AlterModelOptions(
            name='historicalparticipant',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History', 'verbose_name_plural': 'historical Deelnemers'},
        ),
        migrations.AlterModelOptions(
            name='historicalpayment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Geschiedenis', 'verbose_name_plural': 'historical Betalingen'},
        ),
        migrations.AlterModelOptions(
            name='historicalsponsor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History', 'verbose_name_plural': 'historical Sponsors'},
        ),
        migrations.AlterModelOptions(
            name='historicalticket',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Geschiedenis', 'verbose_name_plural': 'historical Tickets'},
        ),
        migrations.AlterModelOptions(
            name='historicaltoernooi',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Geschiedenis', 'verbose_name_plural': 'historical Toernooien'},
        ),
        migrations.AlterModelOptions(
            name='leerling',
            options={'verbose_name': 'Leerling', 'verbose_name_plural': 'Leerlingen'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'get_latest_by': 'pk', 'verbose_name': 'Deelnemer', 'verbose_name_plural': 'Deelnemers'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Betaling', 'verbose_name_plural': 'Betalingen'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='toernooi',
            options={'get_latest_by': 'start_datum', 'ordering': ['-start_datum'], 'verbose_name': 'Toernooi', 'verbose_name_plural': 'Toernooien'},
        ),
    ]
