# Generated by Django 5.0.6 on 2024-09-14 13:09

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0016_rename_historicaltornooi_historicaltoernooi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalparticipant',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='niveau',
        ),
        migrations.AddField(
            model_name='historicalparticipant',
            name='gsm',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0471237769', max_length=128, region=None, verbose_name='GSM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='gsm',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0471237769', max_length=128, region=None, verbose_name='GSM'),
            preserve_default=False,
        ),
    ]
