# Generated by Django 5.0.6 on 2024-09-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0017_remove_historicalparticipant_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsponsor',
            name='toon_knop_op_sponsors_pagina',
            field=models.BooleanField(default=True, verbose_name='Toon knop op sponsors pagina'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='toon_knop_op_sponsors_pagina',
            field=models.BooleanField(default=True, verbose_name='Toon knop op sponsors pagina'),
        ),
    ]
