# Generated by Django 5.0.6 on 2024-09-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0018_historicalsponsor_toon_knop_op_sponsors_pagina_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beurtkaart',
            options={'verbose_name': 'Beurtenkaart', 'verbose_name_plural': 'Beurtenkaarten'},
        ),
        migrations.AlterModelOptions(
            name='historicalbeurtkaart',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History', 'verbose_name_plural': 'historical Beurtenkaarten'},
        ),
        migrations.AddField(
            model_name='historicaltoernooi',
            name='toon_op_site',
            field=models.BooleanField(default=False, verbose_name='Toon op site'),
        ),
        migrations.AddField(
            model_name='toernooi',
            name='toon_op_site',
            field=models.BooleanField(default=False, verbose_name='Toon op site'),
        ),
    ]
