# Generated by Django 5.0.6 on 2024-09-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0019_alter_beurtkaart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipant',
            name='geboortejaar',
            field=models.PositiveSmallIntegerField(default=2000, verbose_name='Geboortejaar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='geboortejaar',
            field=models.PositiveSmallIntegerField(default=2000, verbose_name='Geboortejaar'),
            preserve_default=False,
        ),
    ]
