# Generated by Django 5.0.6 on 2024-09-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0020_historicalparticipant_geboortejaar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToernooiHeaderGroep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(verbose_name='Naam')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
            ],
        ),
        migrations.AddField(
            model_name='historicaltoernooi',
            name='header_groep',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='darts.toernooiheadergroep', verbose_name='Groep in header'),
        ),
        migrations.AddField(
            model_name='toernooi',
            name='header_groep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='toernooien', to='darts.toernooiheadergroep', verbose_name='Groep in header'),
        ),
    ]
