# Generated by Django 5.0.6 on 2024-09-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0021_toernooiheadergroep_historicaltoernooi_header_groep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toernooiheadergroep',
            options={'verbose_name': 'Toernooi Header Groep', 'verbose_name_plural': 'Toernooi Header Groepen'},
        ),
    ]
