# Generated by Django 5.0.6 on 2024-09-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0022_alter_toernooiheadergroep_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltoernooi',
            name='naam_in_header',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Naam in header'),
        ),
        migrations.AddField(
            model_name='toernooi',
            name='naam_in_header',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Naam in header'),
        ),
    ]
