# Generated by Django 5.0.6 on 2024-09-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0023_historicaltoernooi_naam_in_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltoernooi',
            name='header_groep',
        ),
        migrations.RemoveField(
            model_name='toernooi',
            name='header_groep',
        ),
        migrations.AddField(
            model_name='toernooi',
            name='header_groepen',
            field=models.ManyToManyField(related_name='toernooien', to='darts.toernooiheadergroep', verbose_name='Groepen in header'),
        ),
    ]
