# Generated by Django 5.0.6 on 2024-09-23 16:33

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0024_remove_historicaltoernooi_header_groep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToernooiResultaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('richtext', ckeditor.fields.RichTextField(verbose_name='Resultaten')),
            ],
        ),
        migrations.AddField(
            model_name='historicaltoernooi',
            name='resultaten',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='darts.toernooiresultaat', verbose_name='Resultaten'),
        ),
        migrations.AddField(
            model_name='toernooi',
            name='resultaten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='darts.toernooiresultaat', verbose_name='Resultaten'),
        ),
    ]
