# Generated by Django 5.0.6 on 2024-09-23 16:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0025_toernooiresultaat_historicaltoernooi_resultaten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toernooi',
            name='resultaten',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resultaten'),
        ),
        migrations.AlterField(
            model_name='historicaltoernooi',
            name='resultaten',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resultaten'),
        ),
        migrations.DeleteModel(
            name='ToernooiResultaat',
        ),
    ]
