# Generated by Django 5.0.6 on 2024-09-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0026_alter_toernooi_resultaten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toernooi',
            name='header_groepen',
            field=models.ManyToManyField(blank=True, null=True, related_name='toernooien', to='darts.toernooiheadergroep', verbose_name='Groepen in header'),
        ),
    ]
