# Generated by Django 5.0.6 on 2024-09-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0027_alter_toernooi_header_groepen'),
    ]

    operations = [
        migrations.AddField(
            model_name='toernooiheadergroep',
            name='volgorde',
            field=models.SmallIntegerField(default=0, verbose_name='Volgorde'),
        ),
    ]
