# Generated by Django 5.1.1 on 2024-10-22 09:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0028_toernooiheadergroep_volgorde'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nieuws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=120, verbose_name='Titel')),
                ('naam_website', models.CharField(max_length=50, verbose_name='Naam Website')),
                ('link', models.URLField(verbose_name='Artikel URL')),
                ('icon', models.CharField(max_length=40, verbose_name='Bootstrap Icon')),
                ('active', models.BooleanField(verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Nieuws',
                'verbose_name_plural': 'Nieuws',
            },
        ),
        migrations.CreateModel(
            name='HistoricalNieuws',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titel', models.CharField(max_length=120, verbose_name='Titel')),
                ('naam_website', models.CharField(max_length=50, verbose_name='Naam Website')),
                ('link', models.URLField(verbose_name='Artikel URL')),
                ('icon', models.CharField(max_length=40, verbose_name='Bootstrap Icon')),
                ('active', models.BooleanField(verbose_name='Actief')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'historical Nieuws',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
