# Generated by Django 5.1.4 on 2025-02-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0032_trainer_historicaltrainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrainer',
            name='titel',
            field=models.CharField(max_length=50, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='titel',
            field=models.CharField(max_length=50, verbose_name='Titel'),
        ),
    ]
