# Generated by Django 5.1.4 on 2025-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0033_alter_historicaltrainer_titel_alter_trainer_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrainer',
            name='extra_info',
            field=models.CharField(default='Lorem Ipsum', max_length=256, verbose_name='Extra Info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='extra_info',
            field=models.CharField(default='Lorem Ipsum', max_length=256, verbose_name='Extra Info'),
            preserve_default=False,
        ),
    ]
