# Generated by Django 5.1.4 on 2025-02-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0034_historicaltrainer_extra_info_trainer_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrainer',
            name='volgorde',
            field=models.SmallIntegerField(default=0, verbose_name='Volgorde'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='volgorde',
            field=models.SmallIntegerField(default=0, verbose_name='Volgorde'),
        ),
    ]
