# Generated by Django 5.1.4 on 2025-02-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0036_locatie_historicallocatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsponsor',
            name='volgorde_footer',
            field=models.SmallIntegerField(default=0, verbose_name='Volgorde in footer'),
        ),
        migrations.AddField(
            model_name='historicalsponsor',
            name='volgorde_pagina',
            field=models.SmallIntegerField(default=0, verbose_name='Volgorde op pagina'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='volgorde_footer',
            field=models.SmallIntegerField(default=0, verbose_name='Volgorde in footer'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='volgorde_pagina',
            field=models.SmallIntegerField(default=0, verbose_name='Volgorde op pagina'),
        ),
    ]
