# Generated by Django 5.1.3 on 2025-06-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0037_historicalsponsor_volgorde_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100, verbose_name='Titel')),
                ('afbeelding', models.ImageField(upload_to='index_fotos', verbose_name='Afbeelding')),
                ('category', models.CharField(choices=[('dartschool', 'Dartschool'), ('toernooi', 'Toernooi'), ('andere', 'Andere')], default='dartschool', max_length=10, verbose_name='Categorie')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Index Foto',
                'verbose_name_plural': "Index Foto's",
            },
        ),
    ]
