# Generated by Django 5.1.3 on 2025-06-09 15:09

import darts.validators.image_validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0038_indexfoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexfoto',
            name='afbeelding',
            field=models.ImageField(upload_to='index_fotos', validators=[darts.validators.image_validator.validate_image_max_size], verbose_name='Afbeelding'),
        ),
        migrations.CreateModel(
            name='ToernooiFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afbeelding', models.ImageField(upload_to='toernooi_fotos', validators=[darts.validators.image_validator.validate_image_max_size], verbose_name='Foto')),
                ('omschrijving', models.CharField(blank=True, max_length=255, null=True, verbose_name='Omschrijving')),
                ('volgorde', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('toernooi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='darts.toernooi', verbose_name='Toernooi')),
            ],
            options={
                'verbose_name': 'Toernooi Foto',
                'verbose_name_plural': "Toernooi Foto's",
                'ordering': ['volgorde', 'id'],
            },
        ),
    ]
