# Generated by Django 5.1.4 on 2026-07-06 21:20

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts', '0039_alter_indexfoto_afbeelding_toernooifoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100, verbose_name='Titel')),
                ('slug', models.SlugField(unique=True)),
                ('jaar', models.PositiveSmallIntegerField(verbose_name='Jaar')),
                ('intro', ckeditor.fields.RichTextField(blank=True, verbose_name='Intro')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
                ('volgorde', models.SmallIntegerField(default=0, verbose_name='Volgorde')),
                ('locatie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='darts.locatie', verbose_name='Locatie')),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'ordering': ['-jaar', '-volgorde'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLeague',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titel', models.CharField(max_length=100, verbose_name='Titel')),
                ('slug', models.SlugField()),
                ('jaar', models.PositiveSmallIntegerField(verbose_name='Jaar')),
                ('intro', ckeditor.fields.RichTextField(blank=True, verbose_name='Intro')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
                ('volgorde', models.SmallIntegerField(default=0, verbose_name='Volgorde')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locatie', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='darts.locatie', verbose_name='Locatie')),
            ],
            options={
                'verbose_name': 'Geschiedenis',
                'verbose_name_plural': 'historical Leagues',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LeagueDivisie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('volgorde', models.PositiveSmallIntegerField(default=0, verbose_name='Volgorde')),
                ('uitslagen', ckeditor.fields.RichTextField(blank=True, config_name='league_table', verbose_name='Uitslagen')),
                ('stand', ckeditor.fields.RichTextField(blank=True, config_name='league_table', verbose_name='Stand')),
                ('toelichting', ckeditor.fields.RichTextField(blank=True, verbose_name='Toelichting')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisies', to='darts.league', verbose_name='League')),
            ],
            options={
                'verbose_name': 'League Divisie',
                'verbose_name_plural': 'League Divisies',
                'ordering': ['volgorde', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLeagueDivisie',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('volgorde', models.PositiveSmallIntegerField(default=0, verbose_name='Volgorde')),
                ('uitslagen', ckeditor.fields.RichTextField(blank=True, config_name='league_table', verbose_name='Uitslagen')),
                ('stand', ckeditor.fields.RichTextField(blank=True, config_name='league_table', verbose_name='Stand')),
                ('toelichting', ckeditor.fields.RichTextField(blank=True, verbose_name='Toelichting')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='darts.league', verbose_name='League')),
            ],
            options={
                'verbose_name': 'Geschiedenis',
                'verbose_name_plural': 'historical League Divisies',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
