# Generated by Django 5.0.6 on 2024-08-29 17:09

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100, verbose_name='Titel')),
                ('slug', models.SlugField(unique=True)),
                ('beschrijving', ckeditor.fields.RichTextField(verbose_name='Beschrijving')),
                ('vereisten', models.TextField(verbose_name='Vereisten (Elk op een nieuwe lijn)')),
                ('start_datum', models.DateTimeField(verbose_name='Start Datum')),
                ('einde_datum', models.DateTimeField(verbose_name='Eind Datum')),
                ('max_deelnemers', models.IntegerField(verbose_name='Max Deelnemers')),
                ('locatie_kort', models.CharField(max_length=25, verbose_name='Locatie (kort)')),
                ('locatie_lang', models.TextField(verbose_name='Locatie (lang)')),
                ('afbeelding', models.ImageField(upload_to='darts', verbose_name='afbeelding')),
                ('afbeeldingen_download_url', models.URLField(blank=True, null=True, verbose_name='Download afbeeldingen URL')),
                ('vereist_voogd_toestemming', models.BooleanField(default=False, verbose_name='Toestemming van voogd verist')),
                ('enable_inschrijvingen', models.BooleanField(default=False, verbose_name='Inschrijvingen Inschakelen')),
            ],
            options={
                'ordering': ['-start_datum'],
                'get_latest_by': 'start_datum',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvenement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titel', models.CharField(max_length=100, verbose_name='Titel')),
                ('slug', models.SlugField()),
                ('beschrijving', ckeditor.fields.RichTextField(verbose_name='Beschrijving')),
                ('vereisten', models.TextField(verbose_name='Vereisten (Elk op een nieuwe lijn)')),
                ('start_datum', models.DateTimeField(verbose_name='Start Datum')),
                ('einde_datum', models.DateTimeField(verbose_name='Eind Datum')),
                ('max_deelnemers', models.IntegerField(verbose_name='Max Deelnemers')),
                ('locatie_kort', models.CharField(max_length=25, verbose_name='Locatie (kort)')),
                ('locatie_lang', models.TextField(verbose_name='Locatie (lang)')),
                ('afbeelding', models.TextField(max_length=100, verbose_name='afbeelding')),
                ('afbeeldingen_download_url', models.URLField(blank=True, null=True, verbose_name='Download afbeeldingen URL')),
                ('vereist_voogd_toestemming', models.BooleanField(default=False, verbose_name='Toestemming van voogd verist')),
                ('enable_inschrijvingen', models.BooleanField(default=False, verbose_name='Inschrijvingen Inschakelen')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geschiedenis',
                'verbose_name_plural': 'historical evenements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
