# Generated by Django 5.0.6 on 2024-09-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_darts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={'get_latest_by': 'start_datum', 'ordering': ['-start_datum'], 'verbose_name': 'Evenement', 'verbose_name_plural': 'Evenementen'},
        ),
        migrations.AlterModelOptions(
            name='historicalevenement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Geschiedenis', 'verbose_name_plural': 'historical Evenementen'},
        ),
        migrations.AlterModelOptions(
            name='historicalparticipant',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History', 'verbose_name_plural': 'historical Deelnemers'},
        ),
        migrations.AlterModelOptions(
            name='historicalticket',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Geschiedenis', 'verbose_name_plural': 'historical Tickets'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'get_latest_by': 'pk', 'verbose_name': 'Deelnemer', 'verbose_name_plural': 'Deelnemers'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
