# Generated by Django 5.1.1 on 2024-09-25 13:06

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_evenement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipant',
            name='gsm',
            field=phonenumber_field.modelfields.PhoneNumberField(default='123', max_length=128, region=None, verbose_name='GSM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='gsm',
            field=phonenumber_field.modelfields.PhoneNumberField(default='123', max_length=128, region=None, verbose_name='GSM'),
            preserve_default=False,
        ),
    ]
