# Generated by Django 5.1.1 on 2024-09-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_historicalparticipant_gsm_participant_gsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipant',
            name='geboortejaar',
            field=models.PositiveSmallIntegerField(default=1900, verbose_name='Geboortejaar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='geboortejaar',
            field=models.PositiveSmallIntegerField(default=1900, verbose_name='Geboortejaar'),
            preserve_default=False,
        ),
    ]
