# Generated by Django 5.1.1 on 2024-10-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_historicalparticipant_geboortejaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='intro_op_index',
            field=models.CharField(default='lorem ipsum', max_length=400, verbose_name='Intro op homepagina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='intro_op_index',
            field=models.CharField(default='lorem ipsum', max_length=400, verbose_name='Intro op homepagina'),
            preserve_default=False,
        ),
    ]
