# Generated by Django 5.1.1 on 2024-10-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_evenement_intro_op_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='intro_op_index',
            field=models.TextField(max_length=400, verbose_name='Intro op homepagina'),
        ),
        migrations.AlterField(
            model_name='historicalevenement',
            name='intro_op_index',
            field=models.TextField(max_length=400, verbose_name='Intro op homepagina'),
        ),
    ]
