# Generated by Django 5.1.1 on 2024-10-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_historicalticketeigenschap_ticketeigenschap'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='icon',
            field=models.CharField(default='ticket-detailed', max_length=40, verbose_name='Bootstrap Icon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='icon',
            field=models.CharField(default='ticket-detailed', max_length=40, verbose_name='Bootstrap Icon'),
            preserve_default=False,
        ),
    ]
