# Generated by Django 5.1.1 on 2024-10-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_historicalticket_icon_ticket_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalticketeigenschap',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Geschiedenis', 'verbose_name_plural': 'historical Ticket Eigenschappen'},
        ),
        migrations.AlterModelOptions(
            name='ticketeigenschap',
            options={'verbose_name': 'Ticket Eigenschap', 'verbose_name_plural': 'Ticket Eigenschappen'},
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='afbeeldingen_download_url',
        ),
        migrations.RemoveField(
            model_name='historicalevenement',
            name='afbeeldingen_download_url',
        ),
        migrations.AddField(
            model_name='evenement',
            name='enable_standhouder',
            field=models.BooleanField(default=True, verbose_name='Standhouder Inschrijvingen Inschakelen'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='standhouder_inbegrepen',
            field=models.TextField(default='test', verbose_name='Inbegrepen Standhouder (Elk op een nieuwe lijn)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evenement',
            name='standhouder_prijzen',
            field=models.TextField(default='test', verbose_name='Prijzen Standhouder (Elk op een nieuwe lijn)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='enable_standhouder',
            field=models.BooleanField(default=True, verbose_name='Standhouder Inschrijvingen Inschakelen'),
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='standhouder_inbegrepen',
            field=models.TextField(default='test', verbose_name='Inbegrepen Standhouder (Elk op een nieuwe lijn)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='standhouder_prijzen',
            field=models.TextField(default='test', verbose_name='Prijzen Standhouder (Elk op een nieuwe lijn)'),
            preserve_default=False,
        ),
    ]
