# Generated by Django 5.1.1 on 2024-10-07 08:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_alter_historicalticketeigenschap_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='beschrijving',
        ),
        migrations.RemoveField(
            model_name='historicalevenement',
            name='beschrijving',
        ),
        migrations.AddField(
            model_name='evenement',
            name='tekst_sectie_a',
            field=ckeditor.fields.RichTextField(default='test', verbose_name='Tekst Sectie A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evenement',
            name='titel_sectie_a',
            field=models.CharField(default='test', max_length=50, verbose_name='Titel Sectie A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='tekst_sectie_a',
            field=ckeditor.fields.RichTextField(default='test', verbose_name='Tekst Sectie A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='titel_sectie_a',
            field=models.CharField(default='test', max_length=50, verbose_name='Titel Sectie A'),
            preserve_default=False,
        ),
    ]
