# Generated by Django 5.1.1 on 2024-10-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0011_remove_evenement_beschrijving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='disable_ticket',
            field=models.BooleanField(default=False, verbose_name='Schakel ticket uit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='disable_ticket',
            field=models.BooleanField(default=False, verbose_name='Schakel ticket uit'),
            preserve_default=False,
        ),
    ]
