# Generated by Django 5.1.1 on 2024-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0012_historicalticket_disable_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partner_logos/')),
                ('website_url', models.URLField(verbose_name='Website URL')),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='partners',
            field=models.ManyToManyField(to='pokemon.partner', verbose_name='Partners'),
        ),
    ]
