# Generated by Django 5.1.1 on 2024-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_partner_evenement_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='partners',
            field=models.ManyToManyField(blank=True, null=True, to='pokemon.partner', verbose_name='Partners'),
        ),
    ]
