# Generated by Django 5.1.1 on 2024-10-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0014_alter_evenement_partners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalparticipant',
            name='achternaam',
        ),
        migrations.RemoveField(
            model_name='historicalparticipant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalparticipant',
            name='geboortejaar',
        ),
        migrations.RemoveField(
            model_name='historicalparticipant',
            name='gsm',
        ),
        migrations.RemoveField(
            model_name='historicalparticipant',
            name='nummer',
        ),
        migrations.RemoveField(
            model_name='historicalparticipant',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='historicalparticipant',
            name='stad',
        ),
        migrations.RemoveField(
            model_name='historicalparticipant',
            name='straatnaam',
        ),
        migrations.RemoveField(
            model_name='historicalparticipant',
            name='voornaam',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='achternaam',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='geboortejaar',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='gsm',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='nummer',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='stad',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='straatnaam',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='voornaam',
        ),
    ]
