# Generated by Django 5.1.1 on 2024-10-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0015_remove_historicalparticipant_achternaam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipant',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='participant',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
