# Generated by Django 5.1.1 on 2024-10-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0016_historicalparticipant_mail_participant_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='vereisten',
        ),
        migrations.RemoveField(
            model_name='historicalevenement',
            name='vereisten',
        ),
    ]
