# Generated by Django 5.1.4 on 2024-12-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0017_remove_evenement_vereisten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Betaald'), ('open', 'Open'), ('canceled', 'Geannuleerd'), ('expired', 'Verlopen'), ('failed', 'Gefaald'), ('refunded', 'Teruggestort')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Betaald'), ('open', 'Open'), ('canceled', 'Geannuleerd'), ('expired', 'Verlopen'), ('failed', 'Gefaald'), ('refunded', 'Teruggestort')], default='open', max_length=10),
        ),
    ]
