# Generated by Django 5.1.3 on 2025-03-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0018_alter_historicalpayment_status_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='highlight_event',
            field=models.BooleanField(default=False, verbose_name='Highlight Event'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='toon_op_site',
            field=models.BooleanField(default=False, verbose_name='Toon op site'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='volgorde',
            field=models.SmallIntegerField(default=0, verbose_name='Volgorde op pagina'),
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='highlight_event',
            field=models.BooleanField(default=False, verbose_name='Highlight Event'),
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='toon_op_site',
            field=models.BooleanField(default=False, verbose_name='Toon op site'),
        ),
        migrations.AddField(
            model_name='historicalevenement',
            name='volgorde',
            field=models.SmallIntegerField(default=0, verbose_name='Volgorde op pagina'),
        ),
    ]
