# Generated by Django 5.1.3 on 2025-06-08 20:18

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0019_evenement_highlight_event_evenement_toon_op_site_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50, verbose_name='Naam')),
                ('website_url', models.URLField(verbose_name='Website URL')),
                ('info', ckeditor.fields.RichTextField(verbose_name='Info over Sponsor')),
                ('toon_op_index', models.BooleanField(default=True, verbose_name='Toon Op Voorpagina')),
                ('toon_in_footer', models.BooleanField(default=True, verbose_name='Toon in footer')),
                ('toon_op_sponsors_pagina', models.BooleanField(default=True, verbose_name='Toon op sponsor pagina')),
                ('toon_knop_op_sponsors_pagina', models.BooleanField(default=True, verbose_name='Toon knop op sponsors pagina')),
                ('volgorde_footer', models.SmallIntegerField(default=0, verbose_name='Volgorde in footer')),
                ('volgorde_pagina', models.SmallIntegerField(default=0, verbose_name='Volgorde op pagina')),
                ('logo', models.ImageField(upload_to='sponsor', verbose_name='Logo')),
                ('afbeelding', models.ImageField(upload_to='sponsor', verbose_name='afbeelding')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSponsor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('naam', models.CharField(max_length=50, verbose_name='Naam')),
                ('website_url', models.URLField(verbose_name='Website URL')),
                ('info', ckeditor.fields.RichTextField(verbose_name='Info over Sponsor')),
                ('toon_op_index', models.BooleanField(default=True, verbose_name='Toon Op Voorpagina')),
                ('toon_in_footer', models.BooleanField(default=True, verbose_name='Toon in footer')),
                ('toon_op_sponsors_pagina', models.BooleanField(default=True, verbose_name='Toon op sponsor pagina')),
                ('toon_knop_op_sponsors_pagina', models.BooleanField(default=True, verbose_name='Toon knop op sponsors pagina')),
                ('volgorde_footer', models.SmallIntegerField(default=0, verbose_name='Volgorde in footer')),
                ('volgorde_pagina', models.SmallIntegerField(default=0, verbose_name='Volgorde op pagina')),
                ('logo', models.TextField(max_length=100, verbose_name='Logo')),
                ('afbeelding', models.TextField(max_length=100, verbose_name='afbeelding')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'historical Sponsors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
