# Generated by Django 5.1.3 on 2025-06-09 15:17

import darts.validators.image_validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0020_sponsor_historicalsponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afbeelding', models.ImageField(upload_to='evenement_fotos', validators=[darts.validators.image_validator.validate_image_max_size], verbose_name='Foto')),
                ('omschrijving', models.CharField(blank=True, max_length=255, null=True, verbose_name='Omschrijving')),
                ('volgorde', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_evenement', to='pokemon.evenement', verbose_name='Evenement')),
            ],
            options={
                'verbose_name': 'Evenement Foto',
                'verbose_name_plural': "Evenement Foto's",
                'ordering': ['volgorde', 'id'],
            },
        ),
    ]
