# Generated by Django 5.1.4 on 2026-07-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0022_standhouder_wizard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstandhouderinschrijving',
            name='bedrijfsnaam',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bedrijfsnaam'),
        ),
        migrations.AlterField(
            model_name='historicalstandhouderinschrijving',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalstandhouderinschrijving',
            name='naam',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='historicalstandhouderinschrijving',
            name='telefoon',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefoon'),
        ),
        migrations.AlterField(
            model_name='standhouderinschrijving',
            name='bedrijfsnaam',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bedrijfsnaam'),
        ),
        migrations.AlterField(
            model_name='standhouderinschrijving',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='standhouderinschrijving',
            name='naam',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='standhouderinschrijving',
            name='telefoon',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefoon'),
        ),
    ]
