# Generated by Django 5.1.4 on 2026-07-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0023_standhouder_gegevens_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzaalplancel',
            name='colspan',
            field=models.PositiveIntegerField(default=1, verbose_name='Kolom-overspanning'),
        ),
        migrations.AddField(
            model_name='historicalzaalplancel',
            name='rowspan',
            field=models.PositiveIntegerField(default=1, verbose_name='Rij-overspanning'),
        ),
        migrations.AddField(
            model_name='historicalzaalplancel',
            name='verborgen',
            field=models.BooleanField(default=False, verbose_name='Verborgen (deel van samengevoegde cel)'),
        ),
        migrations.AddField(
            model_name='zaalplancel',
            name='colspan',
            field=models.PositiveIntegerField(default=1, verbose_name='Kolom-overspanning'),
        ),
        migrations.AddField(
            model_name='zaalplancel',
            name='rowspan',
            field=models.PositiveIntegerField(default=1, verbose_name='Rij-overspanning'),
        ),
        migrations.AddField(
            model_name='zaalplancel',
            name='verborgen',
            field=models.BooleanField(default=False, verbose_name='Verborgen (deel van samengevoegde cel)'),
        ),
        migrations.AlterField(
            model_name='historicalzaalplancel',
            name='label',
            field=models.CharField(blank=True, max_length=30, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='zaalplancel',
            name='label',
            field=models.CharField(blank=True, max_length=30, verbose_name='Label'),
        ),
    ]
