# Generated by Django 5.1.4 on 2026-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0024_zaalplan_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalzaalplancel',
            name='colspan',
        ),
        migrations.RemoveField(
            model_name='historicalzaalplancel',
            name='rowspan',
        ),
        migrations.RemoveField(
            model_name='historicalzaalplancel',
            name='verborgen',
        ),
        migrations.RemoveField(
            model_name='zaalplancel',
            name='colspan',
        ),
        migrations.RemoveField(
            model_name='zaalplancel',
            name='rowspan',
        ),
        migrations.RemoveField(
            model_name='zaalplancel',
            name='verborgen',
        ),
        migrations.AddField(
            model_name='historicalzaalplancel',
            name='groep',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Groep (samengevoegde cel)'),
        ),
        migrations.AddField(
            model_name='zaalplancel',
            name='groep',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Groep (samengevoegde cel)'),
        ),
    ]
