# Generated by Django 5.1.4 on 2026-07-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0025_zaalplan_groep'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalzaalplancel',
            name='gereserveerd',
            field=models.BooleanField(default=False, verbose_name='Reeds gereserveerd'),
        ),
        migrations.AddField(
            model_name='zaalplancel',
            name='gereserveerd',
            field=models.BooleanField(default=False, verbose_name='Reeds gereserveerd'),
        ),
    ]
