# Generated by Django 5.1.4 on 2026-07-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0027_standhouder_zaalplan_optioneel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstandhoudervraag',
            name='is_borg',
            field=models.BooleanField(default=False, help_text='Markeer als borg: bij een positief antwoord verschijnt op het overzicht een melding dat deze borg niet wordt terugbetaald bij annulatie.', verbose_name='Is borg'),
        ),
        migrations.AddField(
            model_name='standhoudervraag',
            name='is_borg',
            field=models.BooleanField(default=False, help_text='Markeer als borg: bij een positief antwoord verschijnt op het overzicht een melding dat deze borg niet wordt terugbetaald bij annulatie.', verbose_name='Is borg'),
        ),
    ]
