# Generated by Django 5.1.4 on 2026-07-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0028_standhouder_vraag_borg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='standhouder_betaling_verplicht',
            field=models.BooleanField(default=False, help_text='Aan: standhouder betaalt direct online via Mollie na bevestiging. Uit: geen online betaling; de standhouder ontvangt een voorlopige bevestiging per e-mail en jullie nemen manueel contact op.', verbose_name='Online betaling via Mollie'),
        ),
        migrations.AlterField(
            model_name='historicalevenement',
            name='standhouder_betaling_verplicht',
            field=models.BooleanField(default=False, help_text='Aan: standhouder betaalt direct online via Mollie na bevestiging. Uit: geen online betaling; de standhouder ontvangt een voorlopige bevestiging per e-mail en jullie nemen manueel contact op.', verbose_name='Online betaling via Mollie'),
        ),
    ]
